version: '3'
services:

  api:
    build:
      context: .
    volumes:
      - .:/src
    ports:
      - 8080:80
    networks:
      - backend

  worker:
    build:
      context: .
    volumes:
      - .:/src
    environment:
      - API_URL=http://api/
    command: ["poetry", "run", "watchmedo", "auto-restart", "-d", ".", "--recursive", "--", "poetry", "run", "python", "worker.py"]
    working_dir: /src/api
    networks:
      - backend
    depends_on:
      - api
  
networks:
  backend: